version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - UMASK_SET=022 #optional
    volumes:
      - ~/config:/config
      - /yosemite/tvseries:/tv
      - /yosemite/movies:/movies
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 #optional
    volumes:
      - ~/config/config
      - /yosemite/tvseries:/tv
      - /yosemite/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 #optional
    volumes:
      - ~/config:/config
      - /yosemite/movies:/movies
      - /yosemite/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=America/Sao_Paulo
    volumes:
      - ~/config:/config
      - /yosemite:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ~/config:/config
      - /yosemite/downloads:/downloads
    restart: unless-stopped

  calibre:
    image: linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=Europe/London
      - GUAC_USER=abc #optional
      - GUAC_PASS=900150983cd24fb0d6963f7d28e17f72 #optional
    volumes:
      - /path/to/data:/config
    ports:
      - 9090:8080
      - 9091:8081
    restart: unless-stopped
    