version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/plex:/config
      - /yosemite/tvseries:/tv
      - /yosemite/movies:/movies
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    extends:
      file: base.yml
      service: base
    volumes:
      - /home/$USER/config/sonarr/config
      - /yosemite/tvseries:/tv
      - /yosemite/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/radarr:/config
      - /yosemite/movies:/movies
      - /yosemite/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/jackett:/config
      - /yosemite:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    extends:
      file: base.yml
      service: base
    environment:
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ~/config/deluge:/config
      - /yosemite/downloads:/downloads
    restart: unless-stopped

  calibre:
    image: linuxserver/calibre
    container_name: calibre
    extends:
      file: base.yml
      service: base
    volumes:
      - /yosemite/calibre:/config
    ports:
      - 9090:8080
      - 9091:8081
    restart: unless-stopped

  # letsencrypt:
  #   image: linuxserver/letsencrypt
  #   container_name: letsencrypt
  #   cap_add:
  #     - NET_ADMIN
  #   extends:
  #     file: base.yml
  #     service: base
  #   environment:
  #     - URL=theunderthing.tech
  #     - SUBDOMAINS=yosemite,
  #     - VALIDATION=dns
  #     - DNSPLUGIN=cloudflare #optional
  #     - STAGING=false #optional
  #   volumes:
  #     - ~/config/qbittorrent:/config
  #   ports:
  #     - 443:443
  #     - 80:80 #optional
  #   restart: unless-stopped

