version: "2"
services:
  nginx:
    image: linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Sao_Paulo
    volumes:
      - ~/config/nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - UMASK_SET=022 #optional
    volumes:
      - ~/config/plex:/config
      - /yosemite/tvseries:/tv
      - /yosemite/movies:/movies
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 #optional
    volumes:
      - ~/config/sonarr/config
      - /yosemite/tvseries:/tv
      - /yosemite/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 #optional
    volumes:
      - ~/config/radarr:/config
      - /yosemite/movies:/movies
      - /yosemite/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Sao_Paulo
    volumes:
      - ~/config/jackett:/config
      - /yosemite:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 #optional
    volumes:
      ~/config/deluge:/config
      - /yosemite/downloads:/downloads
      - ~/config/bazarr:/config
      - /yosemite/movies:/movies
      - /yosemite/tvseries:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Sao_Paulo
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ~/config/calibre-wen:/config
      - /yosemite/calibre:/books
    ports:
      - 8083:8083
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Sao_Paulo
    volumes:
      - ~/config/tautulli:/config
      - ~/config/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    extends:
      file: base.yml
      service: base
    environment:
      - WEBUI_PORT=5000
    volumes:
      - ~/config/qbittorrent:/config
      - /storage/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 5000:5000
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/prometheus/:/etc/prometheus/
      - ~/data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    extends:
      file: base.yml
      service: base
    depends_on:
      - prometheus
    ports:
      - 3001:3000
    volumes:
      - ~/data/prometheus:/var/lib/grafana
      - ~/config/prometheus:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    user: "104"
